<div id="targetbay_reviews"></div>
<?php $product = Mage::registry('current_product'); ?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $richSnippets = Mage::helper('tracking')->getRichSnippets(); ?>

<?php $productSku = $_helper->productAttribute($product, $product->getSku(), 'sku'); ?>
<?php $productName = $_helper->productAttribute($product, $product->getName(), 'name'); ?>
<?php if(!empty($richSnippets) && $richSnippets['average_score'] > 0): ?>
<div id="<?php echo $productSku; ?>" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
        <span itemprop="bestRating" content="5"></span> 
        <span itemprop="worstRating" content="1"></span> 
        <span itemprop="ratingValue" content="<?php echo $richSnippets['average_score']; ?>"></span> 
        <span itemprop="reviewCount" content="<?php echo $richSnippets['reviews_count']; ?>"></span>
	<div itemprop="itemReviewed" itemscope itemtype="http://schema.org/Thing">
		<span itemprop="name" content="<?php echo $productName; ?>"></span>
	</div>
</div>
<?php if($richSnippets['reviews_count'] > 0): ?>
<?php foreach($richSnippets['reviews']  as $key => $aggregateReviewDetails): ?>
<?php $reviewId = $aggregateReviewDetails->_id; ?>
<?php $reviewTitle = $aggregateReviewDetails->_source->review_title; ?>
<?php $review = $aggregateReviewDetails->_source->review; ?>
<?php $timestamp = $aggregateReviewDetails->_source->timestamp; ?>
<?php $reviewRating = $aggregateReviewDetails->_source->review_rating; ?>
<?php $userName = $aggregateReviewDetails->_source->user_name; ?>
<div itemprop="review" id="<?php echo 'tb-review-'.$key; ?>" itemscope itemtype="http://schema.org/Review" data-reviewid="<?php echo $reviewId; ?>">
        <span itemprop="name" content="<?php echo $reviewTitle; ?>"></span> 
        <span itemprop="description" content="<?php echo $review; ?>"></span> 
        <span itemprop="datePublished" content="<?php echo date('m/d/Y', $timestamp); ?>"></span>
	<div itemprop="itemReviewed" itemscope itemtype="http://schema.org/Thing">
		<span itemprop="name" content="<?php echo $productName; ?>"></span>
	</div>
	<div itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
        <span itemprop="ratingValue" content="<?php echo $reviewRating; ?>"></span> 
        <span itemprop="worstRating" content="1"></span>
        <span itemprop="bestRating" content="5"></span>
	</div>
	<div itemprop="author" itemscope itemtype="http://schema.org/Thing">
        <span itemprop="name" content="<?php echo $userName; ?>"></span>
	</div>
</div>
<?php endforeach; ?>
<?php endif; ?>
<?php else: ?>
<div id="<?php echo $productSku; ?>"></div>
<?php endif; ?>

<?php $questionSnippets = Mage::helper('tracking')->getQuestionSnippets(); ?>

<?php if(!empty($questionSnippets) && $questionSnippets['qa_count'] > 0): ?>
<?php $authorName = $questionSnippets['qa_author']; ?>
<?php foreach($questionSnippets['qa_details']  as $key => $qasDetails): ?>
	<?php $productName = $qasDetails->_source->product_name; ?>
	<?php $questionName = $qasDetails->_source->questions; ?>
	<?php $qasCreatedDate = $qasDetails->_source->timestamp; ?>
	<?php $qasUsername = $qasDetails->_source->user_name; ?>
	<?php $answerArray = $qasDetails->_source->question_answers; ?>
	<?php $qasId = $qasDetails->_id; ?>
	<?php $i = 1; ?>
	<div id="<?php echo 'tb-qas-'.$key; ?>" itemscope itemtype="http://schema.org/Question">

		<span itemprop="name" content="<?php echo $productName; ?>"></span>
		<span itemprop="text" content="<?php echo $questionName; ?>"></span>
		<span itemprop="dateCreated" content="<?php echo date('m/d/Y', $qasCreatedDate); ?>"></span>
		<span itemprop="author" itemscope itemtype="http://schema.org/Person">
			<span itemprop="name" content="<?php echo $qasUsername; ?>"></span>
		</span>
		<?php if(count($answerArray) > 0): ?>
		<span itemprop="answerCount" content="<?php echo count($answerArray); ?>"></span>
		<span itemprop="acceptedAnswer" itemscope itemtype="http://schema.org/Answer" id="<?php echo $qasId.'-0'; ?>">
			<span itemprop="upvoteCount" content="<?php echo $answerArray[0]->upvotes; ?>"></span>
			<span itemprop="text" content="<?php echo $answerArray[0]->answers; ?>"></span>
			<span itemprop="dateCreated" content="<?php echo date('m/d/Y', $answerArray[0]->answer_timestamp); ?>"></span>
			<span itemprop="author" itemscope itemtype="http://schema.org/Person">
				<span itemprop="name" content="<?php echo $authorName; ?>"></span>
			</span>
		</span>
		<?php foreach($answerArray  as $key => $answers): ?>
		<span itemprop="suggestedAnswer" itemscope itemtype="http://schema.org/Answer" id="<?php echo $qasId.'-'.$i; ?>">
			<span itemprop="upvoteCount" content="<?php echo $answers->upvotes; ?>"></span>
			<span itemprop="text" content="<?php echo $answers->answers; ?>"></span>
	  		<span itemprop="dateCreated" content="<?php echo date('m/d/Y', $answers->answer_timestamp); ?>"></span>
			<span itemprop="author" itemscope itemtype="http://schema.org/Person">
				<span itemprop="name" content="<?php echo $authorName; ?>"></span>
			</span>
		</span>
		<?php $i++; endforeach; ?>
		<?php endif; ?>
	</div>
<?php endforeach; ?>
<?php endif; ?>